---
openapi: 3.0.0
info:
  title: API Documentation
  description: REST API // goit-node-hw-rest-api
  version: 1.0.0
servers:
- url: https://virtserver.swaggerhub.com/viapartner/goit-node/1.0.0
  description: gswaggerhub.com
- url: http://localhost:3000/api
  description: localhost
tags:
- name: auth
  description: users controller
- name: contacts
  description: contacts controller
paths:
  /users/register:
    post:
      tags:
      - auth
      summary: User registration
      description: |
        Note: The password must consist of letters of the Latin alphabet (A-z), Arabic numbers (0-9) and special characters, the letter part of the password must contain both lower and uppercase letters, the length of the password must be at least 8 and no more than 16 characters.
      requestBody:
        description: Registration's object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/NewUserRequest'
        required: true
      responses:
        "201":
          description: Created
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewUserResponse'
        "400":
          description: Bad Request / Validation error
        "409":
          description: Conflict / Email in use
components:
  schemas:
    NewUserRequest:
      required:
      - email
      - password
      type: object
      properties:
        email:
          type: string
        password:
          type: string
    NewUserResponse:
      required:
      - email
      - subscription
      type: object
      properties:
        email:
          type: string
        subscription:
          type: string
